// Entry templates for the Monster of the Week Campaign Keeper.
// Field kinds: text, textarea, number, type (datalist + auto-motivation),
// attacks (table), track (harm boxes), countdown, links, image.

const MOTIVATIONS = {
  monster: {
    Beast: "to run wild, destroying and killing",
    Breeder: "to give birth to, bring forth, or create evil",
    Collector: "to steal specific sorts of things",
    Destroyer: "to bring about the end of the world",
    Executioner: "to punish the guilty",
    Parasite: "to infest, control and devour",
    Queen: "to possess and control",
    Sorcerer: "to usurp unnatural power",
    Tempter: "to tempt people into evil deeds",
    Torturer: "to hurt and terrify",
    Trickster: "to create chaos",
  },
  minion: {
    Assassin: "to kill the hunters",
    Brute: "to intimidate and attack",
    Cultist: "to save their own skin at any cost",
    Guardian: "to bar a way or protect something",
    Plague: "to swarm and destroy",
    "Right Hand": "to back up the monster",
    Scout: "to stalk, watch, and report",
    Thief: "to steal and deliver to the monster",
    Traitor: "to betray people",
  },
  phenomenon: {
    Artifact: "to lure people to use or activate it",
    Curse: "to control fate",
    Disease: "to infect people",
    Path: "to lead somewhere",
    Portal: "to send things elsewhere",
    Rift: "to spit things out",
    Vortex: "to draw things in",
  },
  location: {
    Crossroads: "to bring together",
    Deathtrap: "to harm intruders",
    Den: "to harbour monsters",
    Fortress: "to deny entry",
    Hub: "to reveal information",
    Lab: "to create unnatural things",
    Maze: "to confuse and separate",
    Prison: "to contain",
    Road: "to take someone somewhere",
    Sanctuary: "to protect",
    Wilds: "to hide things",
  },
  bystander: {
    Busybody: "to interfere in other people's plans",
    Detective: "to rule out explanations",
    Gossip: "to pass on rumours",
    Helper: "to join the hunt",
    Innocent: "to do the right thing",
    Official: "to be suspicious",
    Skeptic: "to deny supernatural explanations",
    Victim: "to put themselves in danger",
    Witness: "to reveal information",
  },
};

const COUNTDOWN_STEPS = ["Day", "Shadows", "Sunset", "Dusk", "Nightfall", "Midnight"];

const THREAT_TYPES = ["monster", "minion", "phenomenon", "villain", "location", "bystander"];

const TEMPLATES = {
  mystery: {
    label: "Mysteries",
    single: "Mystery",
    icon: "🔍",
    fields: [
      { key: "status", label: "Status", kind: "type", options: ["Planned", "Active", "Solved", "Unsolved"] },
      { key: "concept", label: "Concept", kind: "textarea", hint: "What is going on, in a sentence or two." },
      { key: "hook", label: "Hook", kind: "textarea", hint: "How the hunters get pulled in." },
      { key: "threats", label: "Threats", kind: "links", types: THREAT_TYPES },
      { key: "countdown", label: "Countdown", kind: "countdown" },
      { key: "clues", label: "Clues & Leads", kind: "textarea" },
      { key: "customMoves", label: "Custom Moves", kind: "textarea" },
    ],
  },
  monster: {
    label: "Monsters",
    single: "Monster",
    icon: "👹",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "type", options: Object.keys(MOTIVATIONS.monster), motivations: MOTIVATIONS.monster },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "powers", label: "Powers", kind: "textarea" },
      { key: "attacks", label: "Attacks", kind: "attacks" },
      { key: "armour", label: "Armour", kind: "number" },
      { key: "harm", label: "Harm Capacity", kind: "track" },
      { key: "weakness", label: "Weakness", kind: "textarea" },
      { key: "customMoves", label: "Custom Moves", kind: "textarea" },
    ],
  },
  minion: {
    label: "Minions",
    single: "Minion",
    icon: "🦇",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "type", options: Object.keys(MOTIVATIONS.minion), motivations: MOTIVATIONS.minion },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "master", label: "Serves", kind: "links", types: ["monster", "villain"] },
      { key: "attacks", label: "Attacks", kind: "attacks" },
      { key: "armour", label: "Armour", kind: "number" },
      { key: "harm", label: "Harm Capacity", kind: "track" },
      { key: "customMoves", label: "Custom Moves", kind: "textarea" },
    ],
  },
  phenomenon: {
    label: "Phenomena",
    single: "Phenomenon",
    icon: "🌀",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "type", options: Object.keys(MOTIVATIONS.phenomenon), motivations: MOTIVATIONS.phenomenon },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "effects", label: "Effects", kind: "textarea" },
      { key: "howToStop", label: "How to Stop It", kind: "textarea" },
      { key: "customMoves", label: "Custom Moves", kind: "textarea" },
    ],
  },
  villain: {
    label: "Villains",
    single: "Villain",
    icon: "🎭",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "text" },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "agenda", label: "Agenda", kind: "textarea" },
      { key: "resources", label: "Resources", kind: "textarea" },
      { key: "allies", label: "Allies & Minions", kind: "links", types: ["monster", "minion", "bystander", "villain"] },
      { key: "powers", label: "Powers", kind: "textarea" },
      { key: "attacks", label: "Attacks", kind: "attacks" },
      { key: "armour", label: "Armour", kind: "number" },
      { key: "harm", label: "Harm Capacity", kind: "track" },
      { key: "weakness", label: "Weakness", kind: "textarea" },
      { key: "countdown", label: "Arc Countdown", kind: "countdown" },
    ],
  },
  location: {
    label: "Locations",
    single: "Location",
    icon: "🏚️",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "type", options: Object.keys(MOTIVATIONS.location), motivations: MOTIVATIONS.location },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "features", label: "Notable Features", kind: "textarea" },
      { key: "inhabitants", label: "Found Here", kind: "links", types: THREAT_TYPES },
    ],
  },
  bystander: {
    label: "Bystanders",
    single: "Bystander",
    icon: "🧍",
    fields: [
      { key: "image", label: "Image URL", kind: "image" },
      { key: "type", label: "Type", kind: "type", options: Object.keys(MOTIVATIONS.bystander), motivations: MOTIVATIONS.bystander },
      { key: "motivation", label: "Motivation", kind: "text" },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "knows", label: "What They Know", kind: "textarea" },
      { key: "harm", label: "Harm Capacity", kind: "track" },
    ],
  },
  session: {
    label: "Session Log",
    single: "Session",
    icon: "📜",
    fields: [
      { key: "date", label: "Date Played", kind: "date" },
      { key: "mystery", label: "Mystery", kind: "links", types: ["mystery"] },
      { key: "recap", label: "Recap", kind: "textarea", hint: "Use [[Entry Name]] to link to any entry." },
      { key: "gmNotes", label: "Keeper Notes (private)", kind: "textarea" },
    ],
  },
};
